# docker-compose --project-name botson --env-file .env up -d
version: '3.8'
services:
  api:
    container_name: botson_api
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    container_name: postgres
    hostname: postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - db.env
    volumes:
      - postgres:/var/lib/postrgesql/data
volumes:
  postgres:
    name: 'botson_db'
